[package]
name = "appalachia-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.6.1"
rand = "0.8.5"
saikoro = "1.1.1"
tokio = { version = "1.35.1", features = ["full"] }
